fix
vishenkailya/Sprint_3 pull request #1
Opened 2023-07-16 10:56 UTC by vishenkailya

2023-07-18 10:32 UTC, kadirovgm requested changes

2023-07-18 10:32 UTC, kadirovgm commented on README.md
> +Проверяю:
Можно лучше: в readme лучше добавить описание проекта, использованные библиотеки и зависимости, описание тестов

также советую пользоваться markdown

2023-07-18 10:32 UTC, kadirovgm commented on conftest.py
> +    browser.get('https://stellarburgers.nomoreparties.site/')
нужно исправить: круто что ты сюда вынес setup метод для открытия браузера, но будет еще круче, если ты юда дополнишь и teardown метод для закрытия браузера

Вот пример, как можно:

```
@pytest.fixture()
def driver():
    driver = webdriver.Chrome()
    driver.get(<url main page>)

    yield driver
    driver.quit()
```

2023-07-18 10:32 UTC, kadirovgm commented on conftest.py
> +def login(driver):
супер!

2023-07-18 10:32 UTC, kadirovgm commented on conftest.py
> +def open_registration_form(driver):
можно лучше: можно было дополнить и сделать фикстуру для заполнений формы регистрации

2023-07-18 10:32 UTC, kadirovgm commented on conftest.py
> +        send_keys('ilya_vishnyakov_11@gmail.com')
Можно лучше: тестовые статичные данные лучше выносить в отдельный файл типа [[data.py](http://data.py/)](http://data.py/) или [[urls.py](http://urls.py/)](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-07-18 10:32 UTC, kadirovgm commented on locators.py
> +    REGISTRATION_PASSWORD_INPUT = (By.XPATH, "//fieldset[3]/div/div/input[@name='Пароль']") #Поле для ввода пароля при регистрации
Нужно исправить: вот эти три локатора (17-19 строки) нужно оптимизировать, они не кажутся стабильными, много div-ов, а в остальном хорошие локаторы!

2023-07-18 10:32 UTC, kadirovgm commented on locators.py
> +class LoginPageLocators:
- Можно лучше: класс с локаторами лучше разделить на несколько: например `AuthPageLocators`, `MainPageLocators`
Сейчас это не критично, но в будущем это точно стоит сделать, так как таким образом ты не будешь импортить лишние локаторы в файл с тестами на экран авторизации. Т.е. у каждой страницы должен быть свой класс с локаторами.
    
    При таком подходе код станет лаконичнее, легко поддерживаемой. Ведь у экрана авторизации и у экрана главной могут быть свои NEXT_BUTTON например. Тогда можно будет легко оба обозвать именно так:
    `MainPageLocators.NEXT_BUTTON` и `AuthPageLocators.NEXT_BUTTON`

Сейчас не требуется, просто говорю на будущее

2023-07-18 10:32 UTC, kadirovgm commented on tests/test_go_to_constructor_from_my_account.py
> +        assert login.current_url == 'https://stellarburgers.nomoreparties.site/' \
супер!

2023-07-18 10:32 UTC, kadirovgm commented on tests/test_go_to_my_account.py
> +        login.quit()
можно лучше: если teardown метод login.quit() вынесешь в основную фикстуру, будет супер! (оставил коммет в conftest.py)

2023-07-18 10:32 UTC, kadirovgm commented on tests/test_login.py
> +        assert driver.current_url == 'https://stellarburgers.nomoreparties.site/login'
Можно лучше: проверка того, что URL поменялся на <url> не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-07-18 10:32 UTC, kadirovgm commented on tests/test_login.py
> +    def test_logging_in_from_registration_page_main_page_logged_in(self, driver):
можно лучше: в этих двух тестах одинаковые шаги, можно было бы вынести шаги как отдельную функцию или в helpers.py

2023-07-18 11:05 UTC, vishenkailya commented on locators.py
> +    REGISTRATION_PASSWORD_INPUT = (By.XPATH, "//fieldset[3]/div/div/input[@name='Пароль']") #Поле для ввода пароля при регистрации
Тут всё упёрлось в проблему, что у поля для ввода имени и почты одинаковый тэг name, поэтому пришлось лишнее уточнение с fieldset добавить, чтобы он не потерялся)

2023-07-19 21:52 UTC, kadirovgm requested changes

2023-07-19 21:52 UTC, kadirovgm commented on conftest.py
> +    driver.quit()
нужно исправить: teardown метод закрытия браузера стоило бы прописать в фикстуру driver

2023-07-19 21:52 UTC, kadirovgm commented on locators.py
>      REGISTRATION_EMAIL_INPUT = (By.XPATH, "//fieldset[2]/div/div/input[@name='name']") #Поле для ввода почты при регистрации
можно лучше: а здесь почему не получилось?

2023-07-20 20:13 UTC, kadirovgm approved these changes

2023-07-27 11:34 UTC, merged